# Generated by Django 5.2.4 on 2025-08-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_description'),
        ('suppliers', '0003_backfill_supplier_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', to='suppliers.supplier'),
        ),
    ]
